### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by ftrippel** [smudali/stocks-analysis#1]
Hi smudali,
Would you mind adding a requirements.txt?
Some of the notebooks contain install statements, but the dashboard not so much.
Regards
Florian

**Comment by ftrippel** [comment]
This is what worked for me:

`brew install ta-lib`

and then 

`pip install numpy-financial yfinance jproperties plotly numpy pandas ta-lib yahoo_fin finnhub-python requests pymongo streamlit streamlit_autorefresh sqlalchemy streamlit-aggrid`

It would be even better to fix the versions using `pip freeze`

**Comment by smudali** [comment]
Thanks Florian. I generated the requirements.txt file - please see the attached.

regards
sugath
[requirements.txt](https://github.com/smudali/stocks-analysis/files/13826107/requirements.txt)

**Comment by ftrippel** [comment]
Good. Can you commit it?
I already have a solution, but maybe its helpful for others.

**Comment by smudali** [comment]
> Good. Can you commit it? I already have a solution, but maybe its helpful for others.

Done. thanks
